version: '2'

services:
    web:
        image: lavoweb/php-5.6
        ports:
            - "80:80"
        volumes:
            - /home/debian/.docker/www:/var/www/html
            - /home/debian/config/php.ini:/etc/php5/apache2/conf.d/90-custom.ini

